# Generated by Django 5.0.7 on 2024-08-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productos', models.CharField(max_length=200)),
                ('Precios', models.FloatField(blank=True)),
                ('Stock', models.IntegerField(blank=True)),
            ],
        ),
    ]
